import * as z from "zod";
import { UserRole } from "@prisma/client";

export const LoginSchema = z.object({
  email: z.string().email({
    message: "Email es requerido",
  }),
  password: z.string().min(1, {
    message: "Password es requerido",
  }),
});

export const RegisterSchema = z.object({
  email: z.string().email({
    message: "Email es requerido",
  }),
  password: z.string().min(6, {
    message: "Minimo de 6 caracteres requeridos",
  }),
  nombre: z.string().min(1, {
    message: "Nombre es requerido",
  }),
  apellido: z.string().min(1, {
    message: "Apellido es requerido",
  }),
  role: z.nativeEnum(UserRole).optional(),
});

export const CreateSubmittedFormSchema = z.object({
  formId: z.string(),
  submissionId: z.string(),
});

export const EntidadSchema = z.object({
  codigoEntidad: z.string(),
  fecha: z.any(),
  tipoRelacion: z.any(),
  tipoActividad: z.any(),
  condicionIva: z.any(),
  codigoActividadAfip: z.any(),
  tipoIndustria: z.any(),
  ingresosEnPesos: z.any(),
  fechaCierrePesos: z.any(),
  tipoDePersona: z.any(),
  direccion: z.any(),
  ciudad: z.any(),
  estado: z.any(),
  pais: z.any(),
  codigoPostal: z.any(),
  telefono: z.any(),
  email: z.any(),
  contactoAfa: z.any(),
  titularCuentaBancaria: z.any(),
  bancoCuentaBancaria: z.any(),
  sucursalCuentaBancaria: z.any(),
  numeroCuentaBancaria: z.any(),
  tipoCuentaBancaria: z.any(),
  cbu: z.any(),
  alias: z.any(),
  cuentaEnExterior: z.any(),
  paisCuentaExterior: z.any(),
  iban: z.any(),
  swift: z.any(),
  bancoCorresponsal: z.any(),
  tieneOficinasExterior: z.any(),
  oficinasExterior: z.any(),
  tieneOperacionesExterior: z.any(),
  operacionesExterior: z.any(),
  montoOperacionesExterior: z.any(),
  fechaCierrePesosExterior: z.any(),
  porcentajeExportacionVsTotal: z.any(),
  razonSocial: z.any(),
  tipoSocietario: z.any(),
  fechaConstitucionSociedad: z.any(),
  fechaInscripcionRpc: z.any(),
  datosInscripcionRegistrales: z.any(),
  cotizaEnBolsa: z.any(),
  dondeCotiza: z.any(),
  nombreCompleto: z.any(),
  nacionalidad: z.any(),
  tipoDocumento: z.any(),
  dni: z.any(),
  cuit: z.any(),
  tipoDocumentoAfip: z.any(),
  sexo: z.any(),
  estadoCivil: z.any(),
  fechaNacimiento: z.any(),
  paisNacimiento: z.any(),
  profesion: z.any(),
  oficio: z.any(),
  expuestaPoliticamente: z.any(),
  esPepEnCaracterDe: z.any(),
  conflictoInteresEmpleadosAfa: z.any(),
  descripcionConflictoInteresEmpleadosAfa: z.any(),
  empleadoActualExAfa: z.any(),
  exEmpleadoActualAfa: z.any(),
  familiarComunAfaEntidad: z.any(),
  personalConInteresEconomicoAfa: z.any(),
  personasInteres: z.any(),
  categoriaClub: z.any(),
  nosisPeorSituacion: z.any(),
  nosisCantidadBancos: z.any(),
  nosisMontoTotal: z.any(),
  nosisAntiguedadBCRA: z.any(),
  nosisPeorSituacion12Meses: z.any(),
  nosisCantidadBancos12Meses: z.any(),
  nosisPerfilCumplimientoDeudor: z.any(),
  nosisEsMoroso: z.any(),
  nosisCantidadSinFondosNoPagados6Meses: z.any(),
  nosisMontoSinFondosNoPagados6Meses: z.any(),
  nosisJuiciosCantidad12Meses: z.any(),
  nosisConcursosQuiebrasCantidad12Meses: z.any(),
  nosisScore: z.any(),
  nosisFacturacionEstimada: z.any(),
  nosisProveedorEstado: z.any(),
  nosisFacturasApocrifas: z.any(),
  nosisDeudasFiscales: z.any(),
  nosisPedidoQuebrasCantidad12Meses: z.any(),
  nosisPeorSituacionCon10Porciento12Mesas: z.any(),
  nosisSectorActividadPrincipalDelEmpleador: z.any(),
  nosisSujetoObligado: z.any(),
  nosisPersonaExpuestaPoliticamente: z.any(),
  nosisCantidadHomonimosEnBaseLaFt: z.any(),
  nosisEnlanceHomonimosEnBaseLaFt: z.any(),
  nosisPeorSituacion12MesesBcra: z.any(),
  nosisUltimaActualizacion: z.any(),
});

export const EstadoContableSchema = z.object({
  fechaDesde: z.string(),
  fechaHasta: z.string(),
  cajaBancos: z.any(),
  inversiones: z.any(),
  cuentasPorCobrarAsociados: z.any(),
  cuentasCobrarTerceros: z.any(),
  derechosRecibirServicios: z.any(),
  otrosCreditos: z.any(),
  bienesParaConsumo: z.any(),
  otrosActivos: z.any(),
  inversionesNoCorrientes: z.any(),
  bienesDeUso: z.any(),
  activosIntangibles: z.any(),
  otrosActivosNoCorrientes: z.any(),
  deudas: z.any(),
  fondosConDestinoEspecifico: z.any(),
  previsiones: z.any(),
  deudasNoCorrientes: z.any(),
  fondosConDestinoEspecificoNoCorrientes: z.any(),
  previsionesNoCorrientes: z.any(),
  capital: z.any(),
  reservas: z.any(),
  resultadosNoAsignados: z.any(),
  resultadoDelEjercicio: z.any(),
  recursosIngresos: z.any(),
  gastosOperativos: z.any(),
  resultadosFinancierosPorTenencia: z.any(),
  resultadosExtraordinarios: z.any(),
});
