import * as z from "zod";
import { UserRole } from "@prisma/client";

export const LoginSchema = z.object({
  email: z.string().email({
    message: "Email es requerido",
  }),
  password: z.string().min(1, {
    message: "Password es requerido",
  }),
});

export const RegisterSchema = z.object({
  email: z.string().email({
    message: "Email es requerido",
  }),
  password: z.string().min(6, {
    message: "Minimo de 6 caracteres requeridos",
  }),
  nombre: z.string().min(1, {
    message: "Nombre es requerido",
  }),
  apellido: z.string().min(1, {
    message: "Apellido es requerido",
  }),
  role: z.nativeEnum(UserRole).optional(),
});

export const CreateSubmittedFormSchema = z.object({
  formId: z.string(),
  submissionId: z.string(),
});

export const EntidadSchema = z.object({
  codigoEntidad: z.string(),
  fecha: z.any(),
  tipoRelacion: z.any(),
  tipoActividad: z.any(),
  condicionIva: z.any(),
  codigoActividadAfip: z.any(),
  tipoIndustria: z.any(),
  ingresosEnPesos: z.any(),
  fechaCierrePesos: z.any(),
  tipoDePersona: z.any(),
  direccion: z.any(),
  ciudad: z.any(),
  estado: z.any(),
  pais: z.any(),
  codigoPostal: z.any(),
  telefono: z.any(),
  email: z.any(),
  contactoAfa: z.any(),
  titularCuentaBancaria: z.any(),
  bancoCuentaBancaria: z.any(),
  sucursalCuentaBancaria: z.any(),
  numeroCuentaBancaria: z.any(),
  tipoCuentaBancaria: z.any(),
  cbu: z.any(),
  alias: z.any(),
  cuentaEnExterior: z.any(),
  paisCuentaExterior: z.any(),
  iban: z.any(),
  swift: z.any(),
  bancoCorresponsal: z.any(),
  tieneOficinasExterior: z.any(),
  oficinasExterior: z.any(),
  tieneOperacionesExterior: z.any(),
  operacionesExterior: z.any(),
  montoOperacionesExterior: z.any(),
  fechaCierrePesosExterior: z.any(),
  porcentajeExportacionVsTotal: z.any(),
  razonSocial: z.any(),
  tipoSocietario: z.any(),
  fechaConstitucionSociedad: z.any(),
  fechaInscripcionRpc: z.any(),
  datosInscripcionRegistrales: z.any(),
  cotizaEnBolsa: z.any(),
  dondeCotiza: z.any(),
  nombreCompleto: z.any(),
  nacionalidad: z.any(),
  tipoDocumento: z.any(),
  dni: z.any(),
  cuit: z.any(),
  tipoDocumentoAfip: z.any(),
  sexo: z.any(),
  estadoCivil: z.any(),
  fechaNacimiento: z.any(),
  paisNacimiento: z.any(),
  profesion: z.any(),
  oficio: z.any(),
  expuestaPoliticamente: z.any(),
  esPepEnCaracterDe: z.any(),
  conflictoInteresEmpleadosAfa: z.any(),
  descripcionConflictoInteresEmpleadosAfa: z.any(),
  empleadoActualExAfa: z.any(),
  exEmpleadoActualAfa: z.any(),
  familiarComunAfaEntidad: z.any(),
  personalConInteresEconomicoAfa: z.any(),
  personasInteres: z.any(),
  categoriaClub: z.any(),
  nosisPeorSituacion: z.any(),
  nosisCantidadBancos: z.any(),
  nosisMontoTotal: z.any(),
  nosisAntiguedadBCRA: z.any(),
  nosisPeorSituacion12Meses: z.any(),
  nosisCantidadBancos12Meses: z.any(),
  nosisPerfilCumplimientoDeudor: z.any(),
  nosisEsMoroso: z.any(),
  nosisCantidadSinFondosNoPagados6Meses: z.any(),
  nosisMontoSinFondosNoPagados6Meses: z.any(),
  nosisJuiciosCantidad12Meses: z.any(),
  nosisConcursosQuiebrasCantidad12Meses: z.any(),
  nosisScore: z.any(),
  nosisFacturacionEstimada: z.any(),
  nosisProveedorEstado: z.any(),
  nosisFacturasApocrifas: z.any(),
  nosisDeudasFiscales: z.any(),
  nosisPedidoQuebrasCantidad12Meses: z.any(),
  nosisPeorSituacionCon10Porciento12Mesas: z.any(),
  nosisSectorActividadPrincipalDelEmpleador: z.any(),
  nosisSujetoObligado: z.any(),
  nosisPersonaExpuestaPoliticamente: z.any(),
  nosisCantidadHomonimosEnBaseLaFt: z.any(),
  nosisEnlanceHomonimosEnBaseLaFt: z.any(),
  nosisPeorSituacion12MesesBcra: z.any(),
  nosisUltimaActualizacion: z.any(),
  riesgoPeorSituacion: z.any(),
  riesgoCantidadBancos: z.any(),
  riesgoMontoTotal: z.any(),
  riesgoAntiguedadBCRA: z.any(),
  riesgoPeorSituacion12Meses: z.any(),
  riesgoCantidadBancos12Meses: z.any(),
  riesgoPerfilCumplimientoDeudor: z.any(),
  riesgoEsMoroso: z.any(),
  riesgoCantidadSinFondosNoPagados6Meses: z.any(),
  riesgoMontoSinFondosNoPagados6Meses: z.any(),
  riesgoJuiciosCantidad12Meses: z.any(),
  riesgoConcursosQuiebrasCantidad12Meses: z.any(),
  riesgoScore: z.any(),
  riesgoFacturacionEstimada: z.any(),
  riesgoProveedorEstado: z.any(),
  riesgoFacturasApocrifas: z.any(),
  riesgoDeudasFiscales: z.any(),
  riesgoPedidoQuebrasCantidad12Meses: z.any(),
  riesgoPeorSituacionCon10Porciento12Mesas: z.any(),
  riesgoSectorActividadPrincipalDelEmpleador: z.any(),
  riesgoSujetoObligado: z.any(),
  riesgoPersonaExpuestaPoliticamente: z.any(),
  riesgoCantidadHomonimosEnBaseLaFt: z.any(),
  riesgoEnlanceHomonimosEnBaseLaFt: z.any(),
  riesgoPeorSituacion12MesesBcra: z.any(),
  riesgoUltimaActualizacion: z.any(),
});

export const EstadoContableSchema = z.object({
  fechaDesde: z.any(),
  fechaHasta: z.any(),
  cajaBancos: z.any(),
  inversiones: z.any(),
  cuentasCobrar: z.any(),
  bienesDeCambio: z.any(),
  otrosActivos: z.any(),
  inversionesNoCorrientes: z.any(),
  bienesDeUso: z.any(),
  activosIntangibles: z.any(),
  otrosActivosNoCorrientes: z.any(),
  deudas: z.any(),
  remuneracionesCargasSociales: z.any(),
  cargasFiscales: z.any(),
  deudasBancariasFinancieras: z.any(),
  otrasDeudas: z.any(),
  previsiones: z.any(),
  deudasNoCorrientes: z.any(),
  otrasDeudasNoCorrientes: z.any(),
  deudasBancariasFinancierasNoCorrientes: z.any(),
  previsionesNoCorrientes: z.any(),
  capital: z.any(),
  reservas: z.any(),
  resultadosNoAsignados: z.any(),
  resultadoDelEjercicio: z.any(),
  recursosIngresos: z.any(),
  costoDeVenta: z.any(),
  gastosOperativos: z.any(),
  resultadosFinancierosPorTenencia: z.any(),
  otrosIngresosEgresos: z.any(),
  area: z.any(),
  resultadosExtraordinarios: z.any(),
  impuestoGanancias: z.any(),
});
